Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

-> All the elements inside a array_list must have the same datatype , but for variable_list its not neccessary that all the datatype should be of same type 

In [11]:
import numpy as np
arr= np.array ([1,1.0,'a'])
print (type(arr))
b = [1,1.0,'a']
print(type(b))
for i in arr:
    print(type(i))
for i in b:
    print(type(i))

<class 'numpy.ndarray'>
<class 'list'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'int'>
<class 'float'>
<class 'str'>


In [14]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

arr= np.array ([1,1.0,'a'])
print (type(arr))
b = [1,1.0,'a']
print(type(b))
for i in arr:
    print(type(i))
for i in b:
    print(type(i))



<class 'numpy.ndarray'>
<class 'list'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'int'>
<class 'float'>
<class 'str'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

-> Yes in list the items will have different datatype but in array_list all the item will have only int datatype , and if implicit type casting is not available than the compiler will throw an error 

In [16]:
arr = np.array(b, dtype=int)
for i in arr:
    print(i)

ValueError: invalid literal for int() with base 10: 'a'

Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [27]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

def get_shape(lst):
    if not isinstance(lst, list):
        return ()
    return (len(lst),) + get_shape(lst[0])

shape = get_shape(num_list)
print("Shape of the list:", shape)

print(shape[0]*shape[1])
print('\n\n\n\n',num_array.shape,'\n\n\n\n',num_array.size)




Shape of the list: (2, 3)
6




 (2, 3) 



 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy 
array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [28]:
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [31]:
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
